services:

  db:
    image: postgres:16-alpine
    container_name: clienthub-db
    environment:
      POSTGRES_DB: clientshub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jeff0831
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: clienthub-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/clientshub
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: jeff0831
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

volumes:
  postgres_data:
